# permissions for end users to edit leisures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: leisure-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-leisure
    app.kubernetes.io/part-of: kube-leisure
    app.kubernetes.io/managed-by: kustomize
  name: leisure-editor-role
rules:
- apiGroups:
  - leisure.shuhanghang.com
  resources:
  - leisures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - leisure.shuhanghang.com
  resources:
  - leisures/status
  verbs:
  - get
